### ISSUE TITLE
Hi-res icons (64px)

### ISSUE THREAD

**Issue by DarthWound** [zayronxio/Zafiro-icons#1]
Hello, this new icon theme is stunning. However we really need higher resolutions _(64px is mandatory, 96px-256px are optional)_ for desktops like GNOME. I know that you focus on LXDE and XFCE but a lot of people use GNOME, it would be great to not ignore them. By the way, talking about GNOME, a lot of related icons are missing.

**Comment by zayronxio** [comment]
As soon as possible I will start the raid of icons of higher resolution,
I would appreciate it if you mentioned the icons that you notice are missing

**Comment by DarthWound** [comment]
Great. I'll open another issue for missing icons.

**Comment by zayronxio** [comment]
please install the new version, it is likely not to require adding larger icons. I modified the theme.index, If the problem persists, notify me

**Comment by DarthWound** [comment]
Perfect!
