### ISSUE TITLE
Skype Icon missing

### ISSUE THREAD

**Issue by chandujr** [zayronxio/Zafiro-icons#101]
OS: Arch Linux
DE: Gnome

Skype icon is rendered as a blue circle. Please check the screenshot:
![Screenshot-20220214121159-991x511](https://user-images.githubusercontent.com/14921501/153814901-b4b5b6a8-7d4a-4ee2-816c-7e2e83f19d5a.png)

**Comment by zayronxio** [comment]
issues resolved in commit 70ec6ce
