### ISSUE TITLE
Change inherits line

### ISSUE THREAD

**Issue by erikdubois** [zayronxio/Zafiro-icons#11]
Thanks for adding surfn to the inherits line

`Inherits=gnome,hicolor,Numix,Numix-Circle-Light,Numix-circle,breeze,Surfn`

It solves the issue with 2 icons but since gnome is second in line all missing icons are coming from gnome. Meld is such an icon. Zafiro does not have the icon so gnome kicks in. Gnome icons are not a good match for your beautiful Zafiro icons.

May I suggest the following line up from this article https://arcolinux.com/install-the-zafiro-icon-theme-and-use-the-power-of-inherits/

`Inherits=Surfn,Numix-Circle-Light,Numix-Circle,breeze,gnome,hicolor`

If people have not installed Surfn or Numix or breeze we end up in gnome after all.

**Typo in your inherits - Capital C for Numix-circle**

More info about the effect of the inherits line - visually
https://www.youtube.com/watch?v=c6gB11-iQBA
https://youtu.be/cRo7S2d7ds4

**Comment by zayronxio** [comment]
solved

**Comment by arcolinuxz** [comment]
Thanks 
I am guessing you do not mind that I include this icon theme now on the ArcoLinux iso for all our users.

**Comment by zayronxio** [comment]
It does not bother me, go ahead, thank you
