### ISSUE TITLE
Icons on light theme are not always visible

### ISSUE THREAD

**Issue by tio-trom** [zayronxio/Zafiro-icons#112]
Here it is XFCE with a light theme, using their default text editor:
![2022-06-12_05-17](https://user-images.githubusercontent.com/38043315/173212753-adebc113-ef63-41ee-b7ea-6860827416e1.png)
More:
![2022-06-12_05-18](https://user-images.githubusercontent.com/38043315/173212771-34e4a503-9089-4aa7-8132-9dfab2d18737.png)

Is there an easy fix?

**Comment by zayronxio** [comment]
for light desktops use opendesktop versions

https://www.pling.com/p/1209330/

**Comment by tio-trom** [comment]
Yup we ended up doing that. Why aren't them part of this package? Like all of them into one package? Would be easier to keep track of changes and all that.

**Comment by zayronxio** [comment]
a light and dark version is now available, please try. I await your comments

**Comment by tio-trom** [comment]
Thanks but installing via any AUR package https://aur.archlinux.org/packages/zafiro-icon-theme or https://aur.archlinux.org/packages/zafiro-icon-theme-git it installs no icon theme. You changed something and these packages are broken now. Can you check please? In the meantime I will try the manual install.

**Comment by tio-trom** [comment]
They are being installed correctly I think here:
![2022-07-11_13-17](https://user-images.githubusercontent.com/38043315/178252946-3a93912a-f374-4444-8f7f-6f1a89d13c35.png)
But there is soemthing wrong with the package.

**Comment by tio-trom** [comment]
I see....there should be the Dark and Light folders directly to usr/share/icons folder...even manually you have to add those folders not the master folder ti .local/share/icons. Can you push a fix for this?

**Comment by tio-trom** [comment]
After manually fixing the issue with this package indeed the Zafiro icons work well with a light theme and a dark theme. So from that perspective this issue can be closed. However we need to fix the issue with how you added the Dark and Light themes to the package so that people can properly install this package. Right now they have to know to copy the Dark and Light folders into the proper folder location on their machine.

**Comment by zayronxio** [comment]
try this command

wget -N https://raw.githubusercontent.com/zayronxio/Zafiro-icons/master/Install-Zafiro-Icons.sh && chmod +x Install-Zafiro-Icons.sh && bash ./Install-Zafiro-Icons.sh

**Comment by tio-trom** [comment]
> try this command
> 
> wget -N https://raw.githubusercontent.com/zayronxio/Zafiro-icons/master/Install-Zafiro-Icons.sh && chmod +x Install-Zafiro-Icons.sh && bash ./Install-Zafiro-Icons.sh

I tried. It does not install them...at least they are not visible in XFCE's settings nor in usr/share/icons or .local/share/icons...

**Comment by tio-trom** [comment]
Oh I see the scripts adds them into the .icons folder in the Home directory. That's not where icons are usually stored, but in the above mentioned ones.

**Comment by tio-trom** [comment]
Even if I move that to the proper directory the system can't pick it up since inside the Zafiro master folder there are 2 folders (dark, light) and they need to be in the .local/share/icons....

**Comment by tio-trom** [comment]
I suggest to rename those as Zafiro-Light and Zafiro-Dark and make sure the script copies those folders directly to .local/share/icons or better usr/share/icons

**Comment by zayronxio** [comment]
try now

**Comment by tio-trom** [comment]
Yes now it works great! Mind this line `rm: cannot remove '/home/tio/.local/share/icons/github.com': No such file or directory` the script has a little bug somewhere but is not a big deal I guess. 

Also can you please help with the AUR package now that you changed this. At least to suggest to the maintainer what to add to the PKGBUILD file https://aur.archlinux.org/packages/zafiro-icon-theme-git - so that we make the Zafiro package work.

Thank you!
