### ISSUE TITLE
Icons unchanged after applying

### ISSUE THREAD

**Issue by jankovicgd** [zayronxio/Zafiro-icons#114]
Hello, I have installed the icon pack in Fedora36/Gnome and after applying I am noticing that the gnome text editor and brave browser didn't change. Thanks in advance.

**Comment by zayronxio** [comment]
they are probably flatpak packages

**Comment by jankovicgd** [comment]
Yeah, tried some stuff manually, brave worked, new gnome text editor not really. But I also noticed Wifi icon in settings is missing somehow.
