### ISSUE TITLE
Add Icons for Softmaker (simple copy)

### ISSUE THREAD

**Issue by FeWa-zu** [zayronxio/Zafiro-icons#118]
Icons for the _Softmaker Freeoffice_ are already beautifully designed and integrated, I suggest simply using them for the _full/bought version_ of the program as well, as none will have both programs.
Hence, one could simply assign:

freeoffice-planmaker.svg      for "planmaker-2021"
reeoffice-textmaker.svg        for "textmaker-2021"
freeoffice-presentations.svg for "presentations-2021"

Thanks!

**Comment by zayronxio** [comment]
Thanks for the suggestion, the change has already been made,
