### ISSUE TITLE
35 more icons

### ISSUE THREAD

**Issue by tio-trom** [zayronxio/Zafiro-icons#122]
You can grab them from here https://www.drive.tromsite.com/s/etAzbifKNPbs7dy

Cheers!

**Comment by tio-trom** [comment]
Also can you please push releases when you think there are enough changes? This way package managers can grab the updates. Like AUR can be bumped up to push the new changes to this package.

**Comment by zayronxio** [comment]
I'm sorry I've been a bit absent, the file no longer exists, can you upload it again?

**Comment by tio-trom** [comment]
Sorry about that. Here they are https://www.drive.tromsite.com/s/R2GHfSicLjQsro2
