### ISSUE TITLE
Missing Cinnamon Settings Icons

### ISSUE THREAD

**Issue by WingofaGriffin** [zayronxio/Zafiro-icons#13]
![image](https://user-images.githubusercontent.com/19497824/49463748-36846900-f7c7-11e8-9c1f-4cdf2bbf71c7.png)
![image](https://user-images.githubusercontent.com/19497824/49463803-5320a100-f7c7-11e8-826b-e3476a516a62.png)
![image](https://user-images.githubusercontent.com/19497824/49463838-66cc0780-f7c7-11e8-9e21-3d4de3425f63.png)

Likely has a good amount of overlap with other GNOME-like desktops.

**Comment by zayronxio** [comment]
this new version adds the icons you request
