### ISSUE TITLE
[request] Several icons, including GNOME apps

### ISSUE THREAD

**Issue by DarthWound** [zayronxio/Zafiro-icons#2]
**GNOME News**
Icon=gnome-news

**GNOME Calendar**
Icon=org.gnome.Calendar

**Gedit**
Icon=gedit

**Evolution**
Icon=evolution

**GNOME Boxes**
Icon=gnome-boxes

**Deja-Dup**
Icon=org.gnome.DejaDup

**GNOME ToDo**
Icon=org.gnome.Todo

**GNOME Tweaks**
Icon=gnome-tweak-tool

**Baobab**
Icon=baobab

**Dconf Editor**
Icon=dconf-editor

**GNOME Clocks**
Icon=org.gnome.clocks

**GNOME Logs**
Icon=gnome-logs

**Mailnag**
Icon=mailnag

**GNOME Weather**
Icon=org.gnome.Weather

**GNOME Characters**
Icon=gnome-characters

**YaST**
Icon=yast

___

![capture d ecran de 2018-01-29 04-38-37](https://user-images.githubusercontent.com/1771322/35493290-6d1c5e0e-04b2-11e8-80cc-5f8e861951dd.png)
![capture du 2018-01-29 04-39-12](https://user-images.githubusercontent.com/1771322/35493291-6d37e674-04b2-11e8-9fcf-e0bbec753cf9.png)

___

PS: Some default GNOME apps are missing as I removed them from my computers.

**Comment by zayronxio** [comment]
the mentioned icons have been added, thanks
