### ISSUE TITLE
Missing Some Icons

### ISSUE THREAD

**Issue by onrc** [zayronxio/Zafiro-icons#23]
Hello, thanks you for the great job! Here some missing icons;

- Geary Email Client
- Nextcloud Desktop Client
- Joplin
- Neovim
- Telegram

**Comment by zayronxio** [comment]
most of the icons you request are already in the pack, you probably need to create symbolic links to other icon names, I would appreciate if you provide me with the names of the icons as they appear in the files in the / usr / share / applications directory
