### ISSUE TITLE
[request] Jetbrains Icons request

### ISSUE THREAD

**Issue by TrackRunny** [zayronxio/Zafiro-icons#35]
Please try and add the whole jetbrains suite for icons if you have time to do that. I only found that I only have Pycharm and webstorm. I am missing rubymine, and some others. Please consider trying to add the full jetbrains suite to the icons.

![image](https://user-images.githubusercontent.com/45835198/63066853-0b5b2900-bec1-11e9-9c6d-6b5627854c50.png)

Those are what I have so far.

**Comment by heregoesnoth** [comment]
Please!

**Comment by kgidwani** [comment]
Please!
