### ISSUE TITLE
Icons don't work well in dark theme

### ISSUE THREAD

**Issue by Bluskript** [zayronxio/Zafiro-icons#37]
![image](https://user-images.githubusercontent.com/52386117/65837566-e7b03e80-e2c6-11e9-989d-5b80bf993d5b.png)
your icon theme is amazing, but it would be great if these invisible icons get fixed in the future!

**Comment by zayronxio** [comment]
wait for this change next week, regards

**Comment by Kodehawa** [comment]
Any news on this?

**Comment by Bluskript** [comment]
**nudge**

**Comment by Kodehawa** [comment]
*poke*

**Comment by Bluskript** [comment]
**bump**

**Comment by mrmatteastwood** [comment]
This issue also affects the notification icons for Dropbox and Nextcloud with I would guess pretty much any theme, because themes' panels most often have dark backgrounds.
![iconproblems](https://user-images.githubusercontent.com/22120259/86531757-4644c180-bec4-11ea-8bd1-d1fae0471fe8.png)

Love this icon theme! Hoping for a fix soon.

**Comment by Hasshu** [comment]
That's one long week, I must say... @zayronxio Any updates?

**Comment by Kodehawa** [comment]
The longest week on history

**Comment by zayronxio** [comment]
hahaha sorry, I had lost sight of this problem, in the next update I will launch correction

**Comment by Bluskript** [comment]
2020 has redeemed itself.

**Comment by mrmatteastwood** [comment]
Hey, that's awesome! :-) Love this icon set.

**Comment by mrmatteastwood** [comment]
Guys! I discovered a workaround that might alleviate the problem in some apps. It does work for me with the NextCloud tray icon! You need to run qt5ct ("Qt5 Settings") on your system, and on the "Icon Theme" tab, you can change icon sets used for Qt5 apps. This applies to NextCloud, I presume Dropbox, VLC, Simplescreenrecorder and a bunch of others. That way, you might fix icon issues in some apps while keeping Zafiro for most of your system. Might do the trick!

**Comment by Hasshu** [comment]
It's only me, or the newest v1.2.1 remains unusable with dark themes?

![Screenshot_20211112](https://user-images.githubusercontent.com/17361080/141519028-ae002c1d-4b58-48c6-84b0-1ada99553c5b.png)

That's how KWrite looks with the default Breeze Dark theme (KDE Plasma v5.22.5) and the new "dark" version of Zafiro.

**Comment by Hasshu** [comment]
I'm not sure whether v1.2.3 or the recent KDE Frameworks update did it, but the dark version of Zafiro seems to be working properly now (after adding "breeze-dark" to the inherits list).

@zayronxio By the way, GitHub still lacks the recent releases, while the OpenDesktop changelog calls the newest version "v0.2.3".
