### ISSUE TITLE
New Icons that we made

### ISSUE THREAD

**Issue by tiotrom** [zayronxio/Zafiro-icons#38]
Hi,
We contacted you before but didn't get a reply. We want to contribute. We are making more and more icons - they are all here https://www.cloud.tromsite.com/s/KaJ437rTNbn487A (to our nextcloud)

We named them all to match the .desktop files for the respective applications they represent.
If you tell us how we can directly add them to this package we will make more and more. We have a custom Linux distro that uses this icon pack and we want to contribute. 

Please let us know. Cheers!

**Comment by zayronxio** [comment]
good day. I can't visualize anything.
file not Found

**Comment by tiotrom** [comment]
True I apologize we are moving them as I type. I'll update in a few hours with a link that will work 100% and we won't change that link again. Cheers!

**Comment by tiotrom** [comment]
Ok, the working link - https://www.cloud.tromsite.com/s/KaJ437rTNbn487A - sorry for that. It works now and we are going to start working on more and more icons.

**Comment by zayronxio** [comment]
many of the icons are already in the set, even with the same name. add some of your icons anyway, a few were modified, in the following versions I will add more. regards

**Comment by tiotrom** [comment]
Awesome! I will always cross-check with the latest github update from now on, and only add the ones that are missing. You can also check the ones we made since we focus on replicating them to look more like the original but in this Zafiro style ;) - so maybe you may like them more and want to replace. Up to you and thank you!

**Comment by tiotrom** [comment]
More icos that we made ;) - and we are making more and more. You can always check the folder and sort by "modified date". The "add to tromjaro" folder are icons that we have to add to our website (so they are newer in general) - so you know. This is our website that uses this icon pack https://www.tromjaro.com/apps/

And, should I remind you from time to time about these? Or are you going to have a look at the folder yourself from time to time? :) - I don't mind dropping a comment here when we make more icons.

Cheers!

**Comment by zayronxio** [comment]
Thank you very much, I added some others have served as a base, I thank you for your inter, I hope to continue to count on your support

**Comment by tiotrom** [comment]
Awesome! For sure you will count on our support. We are a very small team but we are active. We will make more and more. Please check that folder from time to time ;) - cheers!

**Comment by tiotrom** [comment]
We have some 150 new icons for you https://www.cloud.tromsite.com/s/pqed9rinPTj2dko that we did for the past 1 month or so ;). Mind you some icons were already in your icon pack but they were duplicates. We are making original icons, no duplicates, that resemble the app itself. I will give you one example: Marble https://www.tromjaro.com/marble/ - this is a "map" like application and their original icon looks like this:
![image](https://user-images.githubusercontent.com/34804533/78414597-2a0f5b00-761d-11ea-9200-6a5fc497891a.png)

In Zafiro's icon pack it looks like this:
![image](https://user-images.githubusercontent.com/34804533/78414637-6642bb80-761d-11ea-8063-a19cad3b80d6.png)

Which is 100% identical to Gnome Maps (since it is a symlink to that icon in Zafiro's icons). It is ok since it is a "maps" icon, but why not have an original icon? :)

This is the icon we made:
![image](https://user-images.githubusercontent.com/34804533/78414669-8ecab580-761d-11ea-87a9-4a8e8442abc0.png)

It resembles the original one.

So, if you can please use the icons we did from that folder regardless if some of the icons are already in the Zafiro's pack since we make them like the original so we don't use "generic" icons. Maybe you could do that ;)

Ok, we will make more and more since our Linux Distro: TROMjaro is quite active and we love this icon pack. We have 2 designers and these girls are doing a wonderful job with these icons and they love doing it ;). I hope you can push an update soon!

Cheers!

**Comment by zayronxio** [comment]
thanks for this icon, they change some colors, but basically it is the same icon, very nice

**Comment by tiotrom** [comment]
Please see the https://www.cloud.tromsite.com/s/pqed9rinPTj2dko for the 150 new icons we made ;) - I hope it is helpful

**Comment by zayronxio** [comment]
of course yes, I already like many of these to the new update

**Comment by tiotrom** [comment]
160 new icons that we made since my last post. All here https://www.cloud.tromsite.com/s/pqed9rinPTj2dko - please add when you can. Cheers!

**Comment by zayronxio** [comment]
the link no longer works

**Comment by tio-trom** [comment]
We moved our nextcloud a few months ago. This works https://www.drive.tromsite.com/s/bQTzsqfeqny2Qpt
