### ISSUE TITLE
Application-side icons on dark themes look bad

### ISSUE THREAD

**Issue by tiotrom** [zayronxio/Zafiro-icons#50]
This is how Inkscape looks like with a dark theme
![image](https://user-images.githubusercontent.com/34804533/78414864-9474cb00-761e-11ea-9eb4-a75a6e9b69d5.png)

Can this be fixed with Zafiro?

**Comment by tiotrom** [comment]
This is with breeze-dark
![image](https://user-images.githubusercontent.com/34804533/78414911-d43bb280-761e-11ea-8e70-e9bdeb634479.png)

And this with Elementary icon
![image](https://user-images.githubusercontent.com/34804533/78414924-e61d5580-761e-11ea-93aa-e72c904995bc.png)

**Comment by zayronxio** [comment]
versions for dark themes are now available
[here](https://github.com/zayronxio/Zafiro-icons/releases/tag/1.2)

#
