### ISSUE TITLE
LibreOffice Writer Icon

### ISSUE THREAD

**Issue by jcuenod** [zayronxio/Zafiro-icons#52]
For some reason, the LibreOffice Writer icon in my application switcher is the generic LO icon instead of the Writer icon. In the application launcher, it's correct. So, maybe something's wrong with my `.desktop` file but I just thought I'd post the issue here to see if you know what the problem might be...

**Comment by zayronxio** [comment]
is snap package?

**Comment by jcuenod** [comment]
No, I'm using Arch.

**Comment by zayronxio** [comment]
can you try checking the icon name in the .desktop file?

**Comment by jcuenod** [comment]
Here's an extract of `/usr/share/applications/libreoffice-writer.desktop`:

```
[Desktop Entry]
Version=1.0
Terminal=false
Icon=libreoffice-writer
Type=Application
```

There's also stuff for a new document that uses `libreoffice-document-new`. I now realise that it's possible that the problem might actually be `/usr/share/applications/libreoffice-startcenter.desktop` which defines actions (including writer) and defines the startcenter icon in the main desktop entry which is presumably inherited by all the actions.

**Comment by jcuenod** [comment]
This issue looks like it's actually something between LO and GTK and only occurs on Wayland so I'm going to close (cf. https://gitlab.gnome.org/GNOME/gtk/-/issues/767).
