### ISSUE TITLE
[request] Systray icons for Chrome, Slack and Teams

### ISSUE THREAD

**Issue by CHgsd** [zayronxio/Zafiro-icons#56]
There are three application I noticed missing systray icons for:
1. Chrome
2. Slack
3. MS Teams
For inspiration, the versions in Papirus look quite good I think. No hurry, just documenting per the readme. I would also be willing to make an attempt at these if desired.

**Comment by zayronxio** [comment]
sorry but i don't identify the ms-teams icons

**Comment by CHgsd** [comment]
If you are asking about what the software is, it is https://en.wikipedia.org/wiki/Microsoft_Teams
As for the names, based on Papirus and other icon packages, I see these:

apps folders:
- teams.svg
- teams-for-linux.svg (symlink of teams.svg)

panel folders:
- teams-for-linux-tray.svg
- teams-tray-activity.svg
- teams-tray-noactivity.svg

Thanks!
