### ISSUE TITLE
Icon request for kitty terminal emulator

### ISSUE THREAD

**Issue by xulongwu4** [zayronxio/Zafiro-icons#64]
Hi, thanks for this amazing theme. I have enjoyed it very much.

I hope you can add a icon for the kitty terminal emulator. The official icon can be found on this page: https://sw.kovidgoyal.net/kitty/conf.html

Your great work is highly appreciated :)

**Comment by allallston** [comment]
I came here today to also request this.

**Comment by evanfreed** [comment]
If you're content with the standard terminal logo until the official icon is supported you can work around this doing the following:

```shell
cd /usr/share/icons/Zafiro-icons-1.1/apps/scalable/
ln -s terminal.svg kitty.svg
```
