### ISSUE TITLE
[Icon adjust] Remove messages number from Telegram icon

### ISSUE THREAD

**Issue by flakesrc** [zayronxio/Zafiro-icons#75]
This gets ugly in large numbers, and practically useless in the telegram, because when you participate in many groups, there will always be a huge amount of unread messages: [Image](https://i.imgur.com/Hq3PSV8.png)

And in tray icons, the number of messages is impossible to read, as it is very small, instead, you could put some red dot or something like that, to know that there are unread messages: [Image](https://i.imgur.com/V2BFVBt.png)

PS: I am assuming that these message numbers are part of the icon features

**Comment by zayronxio** [comment]
I'm sorry, this is not solved by modifying the icons
