### ISSUE TITLE
New icons and a question

### ISSUE THREAD

**Issue by tiotrom** [zayronxio/Zafiro-icons#77]
We are continuing to make icons for TROMjaro.com, here https://www.drive.tromsite.com/s/2D3PR85P9n8qbgp - and we will add tens more the following days.

A question: can you push some releases from time to time? It may be easier for us to implement the icon pack in TROMjaro.
Cheers!

**Comment by tiotrom** [comment]
Is ok we can use the AUR git package  https://aur.archlinux.org/packages/zafiro-icon-theme-git/#news

**Comment by zayronxio** [comment]
I have no problem,

**Comment by TROMsite** [comment]
You can close this issue. My above "Tio" account is not reachable at the moment so I can't close it ;)
