### ISSUE TITLE
 [Icon Request] Database Files

### ISSUE THREAD

**Issue by manoelpqueiroz** [zayronxio/Zafiro-icons#88]
Can't thank you enough for how complete this icon package is, almost all programs I use on a daily basis are covered (and I'm not a person that tends to use well-known programs!).

One of the small nitpicks I have that I deem reasonable enough to bring here is the lack of an icon for database files. There is a comprehensive list [here](https://fileinfo.com/filetypes/database), but in my case it's mostly `.db` and `.anki` files, which fall back to the default Breeze style on my KDE desktop:

![image](https://user-images.githubusercontent.com/23669137/131887740-7dba4159-acd1-4cae-9ca1-35b3d53411fd.png)

I did a quick search for terms like `database`, `db` or `sql` in the `.local/share/icons/apps/scalale` folder, but only came with a MySQL Workbench icon.

Either way, I can't thank you enough for providing us this great package, have you ever considered getting more people to help you with new icons that are requested? I've recently started dealing with vector graphics and sounds like coming up with missing icons for this project could help me improve my skills without overwhelming me technically.

**Comment by zayronxio** [comment]
do you know the name of the icon?
