### ISSUE TITLE
The Files/Nautilus icon changed?

### ISSUE THREAD

**Issue by tio-trom** [zayronxio/Zafiro-icons#90]
![2021-09-13_02-04](https://user-images.githubusercontent.com/38043315/133007141-052a7c8b-d52a-4f0f-aa66-5f3a10de4e34.png)

I think the original icon was far better. I am wondering why the change.

**Comment by jcuenod** [comment]
I'll just add my support to this... The new icon looks too much like a security related app (looks like a lock to me).

**Comment by jcuenod** [comment]
The commit is here: https://github.com/zayronxio/Zafiro-icons/commit/500dc6a51b95883df3eace8de372f59474d2b744#diff-469d762e13358871dba93de2389471758efbc9d0339ee93ef9bfbf3bc466a857

Seems like it was changed in a large trove.

**Comment by zayronxio** [comment]
return to the previous icon, thanks for your opinions
