### ISSUE TITLE
[Icon request] Xournal++

### ISSUE THREAD

**Issue by botsunny** [zayronxio/Zafiro-icons#98]
I have been using this icon pack since I started using Linux, so thank you so much!

The most common app that I use that does not have an icon yet is Xournal++, which is an amazing note-taking application with handwriting support. I will be eternally grateful if it is added!

[Github page](https://github.com/xournalpp/xournalpp)
[Github.io page](https://xournalpp.github.io/)
![image](https://user-images.githubusercontent.com/71499037/151167522-56fd956e-c97e-4756-a694-7d234a6acb69.png)

**Comment by tio-trom** [comment]
We did it, alongside 70+ more new icons. See https://github.com/zayronxio/Zafiro-icons/issues/99
