### ISSUE TITLE
77 new icons done

### ISSUE THREAD

**Issue by tio-trom** [zayronxio/Zafiro-icons#99]
We've made 77 new icons https://www.drive.tromsite.com/s/eBHzFk3699NJmaD if you can add them to the package. Cheers!

**Comment by tio-trom** [comment]
EDIT: We have done 20 or so more. Here https://www.drive.tromsite.com/s/wY7DELW7XMHSMXq you can use the last 100 or so. We won't do new ones for now so I won't update this for the time being. Cheers!

**Comment by zayronxio** [comment]
have already been added
